"""add task_dependencies table

Revision ID: 0bc409987f13
Revises: f5918cf0f3ba
Create Date: 2026-07-08 07:54:02.398502

"""
from alembic import op
import sqlalchemy as sa


revision = '0bc409987f13'
down_revision = 'f5918cf0f3ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_task_id', sa.Integer(), nullable=False),
    sa.Column('to_task_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('finish_to_start', name='dependencytype', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['to_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_task_id', 'to_task_id', name='uq_task_dependency_edge')
    )
    # migrate legacy single-FK dependencies into the new table (ADR-0005)
    op.execute(
        """
        INSERT INTO task_dependencies (from_task_id, to_task_id, type, created_at)
        SELECT depends_on, id, 'finish_to_start', CURRENT_TIMESTAMP
        FROM tasks
        WHERE depends_on IS NOT NULL AND depends_on != id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
